### ISSUE TITLE
SpreadRDD failure - IPs are not equal when using h2o_context(sc)

### ISSUE THREAD

**Issue by cazjck** [h2oai/sparkling-water#473]
I have the issues  IPs are not equal . I'm using Spark  with StandAlone mode include linux and windown OS.
Spark : 2.2.0
H2o: 3.14.0.2
sparklingwater for R: 2.2.0

I download sparklingwater and using option "rsparkling.sparklingwater.location":
options(rsparkling.sparklingwater.location = "packages/sparkling-water-2.2.0/assembly/build/libs/sparkling-water-assembly_2.11-2.2.0-all.jar")

` Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/11/23 17:42:53 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 5364@isadmin
17/11/23 17:42:53 INFO SignalUtils: Registered signal handler for TERM
17/11/23 17:42:53 INFO SignalUtils: Registered signal handler for HUP
17/11/23 17:42:53 INFO SignalUtils: Registered signal handler for INT
17/11/23 17:42:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/11/23 17:42:54 WARN Utils: Your hostname, isadmin resolves to a loopback address: 127.0.1.1; using 172.18.12.179 instead (on interface eth0)
17/11/23 17:42:54 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
17/11/23 17:42:54 INFO SecurityManager: Changing view acls to: clientA,clientB
17/11/23 17:42:54 INFO SecurityManager: Changing modify acls to: clientA,clientB
17/11/23 17:42:54 INFO SecurityManager: Changing view acls groups to: 
17/11/23 17:42:54 INFO SecurityManager: Changing modify acls groups to: 
17/11/23 17:42:54 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(isadmin, khanhdpham.pa); groups with view permissions: Set(); users  with modify permissions: Set(isadmin, khanhdpham.pa); groups with modify permissions: Set()
17/11/23 17:42:54 INFO TransportClientFactory: Successfully created connection to khanhpham2982/172.18.4.34:4619 after 37 ms (0 ms spent in bootstraps)
17/11/23 17:42:54 INFO SecurityManager: Changing view acls to: clientA,clientB
17/11/23 17:42:54 INFO SecurityManager: Changing modify acls to: clientA,clientB
17/11/23 17:42:54 INFO SecurityManager: Changing view acls groups to: 
17/11/23 17:42:54 INFO SecurityManager: Changing modify acls groups to: 
17/11/23 17:42:54 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(isadmin, khanhdpham.pa); groups with view permissions: Set(); users  with modify permissions: Set(isadmin, khanhdpham.pa); groups with modify permissions: Set()
17/11/23 17:42:54 INFO TransportClientFactory: Successfully created connection to khanhpham2982/172.18.4.34:4619 after 2 ms (0 ms spent in bootstraps)
17/11/23 17:42:54 INFO DiskBlockManager: Created local directory at /tmp/spark-04ceee59-dbf1-4268-ab0d-b03450184bfb/executor-8a297f16-c115-4af1-8fb1-0095cad286ed/blockmgr-4315229e-62fc-41c1-ad91-ee71df813331
17/11/23 17:42:54 INFO MemoryStore: MemoryStore started with capacity 1458.6 MB
17/11/23 17:42:54 INFO CoarseGrainedExecutorBackend: Connecting to driver: spark://CoarseGrainedScheduler@khanhpham2982:4619
17/11/23 17:42:54 INFO WorkerWatcher: Connecting to worker spark://Worker@172.18.12.179:40782
17/11/23 17:42:54 INFO TransportClientFactory: Successfully created connection to /172.18.12.179:40782 after 13 ms (0 ms spent in bootstraps)
17/11/23 17:42:54 INFO WorkerWatcher: Successfully connected to spark://Worker@172.18.12.179:40782
17/11/23 17:42:54 INFO CoarseGrainedExecutorBackend: Successfully registered with driver
17/11/23 17:42:54 INFO Executor: Starting executor ID 2 on host 172.18.12.179
17/11/23 17:42:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45216.
17/11/23 17:42:54 INFO NettyBlockTransferService: Server created on 172.18.12.179:45216
17/11/23 17:42:54 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
17/11/23 17:42:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(2, 172.18.12.179, 45216, None)
17/11/23 17:42:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(2, 172.18.12.179, 45216, None)
17/11/23 17:42:55 INFO BlockManager: Initialized BlockManager: BlockManagerId(2, 172.18.12.179, 45216, None)
17/11/23 17:43:03 INFO CoarseGrainedExecutorBackend: Got assigned task 3
17/11/23 17:43:03 INFO CoarseGrainedExecutorBackend: Got assigned task 13
17/11/23 17:43:03 INFO Executor: Running task 13.0 in stage 0.0 (TID 13)
17/11/23 17:43:03 INFO Executor: Running task 3.0 in stage 0.0 (TID 3)
17/11/23 17:43:03 INFO Executor: Fetching spark://khanhpham2982:4619/jars/sparklyr-2.2-2.11.jar with timestamp 1511433766192
17/11/23 17:43:03 INFO TransportClientFactory: Successfully created connection to khanhpham2982/172.18.4.34:4619 after 18 ms (0 ms spent in bootstraps)
17/11/23 17:43:03 INFO Utils: Fetching spark://khanhpham2982:4619/jars/sparklyr-2.2-2.11.jar to /tmp/spark-04ceee59-dbf1-4268-ab0d-b03450184bfb/executor-8a297f16-c115-4af1-8fb1-0095cad286ed/spark-7b67aabe-0729-4075-adee-f48abf57b9f6/fetchFileTemp443956183111607150.tmp
17/11/23 17:43:04 INFO Utils: Copying /tmp/spark-04ceee59-dbf1-4268-ab0d-b03450184bfb/executor-8a297f16-c115-4af1-8fb1-0095cad286ed/spark-7b67aabe-0729-4075-adee-f48abf57b9f6/-14449446091511433766192_cache to /usr/local/spark/work/app-20171123174231-0010/2/./sparklyr-2.2-2.11.jar
17/11/23 17:43:04 INFO Executor: Adding file:/usr/local/spark/work/app-20171123174231-0010/2/./sparklyr-2.2-2.11.jar to class loader
17/11/23 17:43:04 INFO Executor: Fetching spark://khanhpham2982:4619/jars/sparkling-water-assembly_2.11-2.2.0-all.jar with timestamp 1511433766192
17/11/23 17:43:04 INFO Utils: Fetching spark://khanhpham2982:4619/jars/sparkling-water-assembly_2.11-2.2.0-all.jar to /tmp/spark-04ceee59-dbf1-4268-ab0d-b03450184bfb/executor-8a297f16-c115-4af1-8fb1-0095cad286ed/spark-7b67aabe-0729-4075-adee-f48abf57b9f6/fetchFileTemp2722361594718744173.tmp
17/11/23 17:43:35 INFO Utils: Copying /tmp/spark-04ceee59-dbf1-4268-ab0d-b03450184bfb/executor-8a297f16-c115-4af1-8fb1-0095cad286ed/spark-7b67aabe-0729-4075-adee-f48abf57b9f6/-16900776211511433766192_cache to /usr/local/spark/work/app-20171123174231-0010/2/./sparkling-water-assembly_2.11-2.2.0-all.jar
17/11/23 17:43:35 INFO Executor: Adding file:/usr/local/spark/work/app-20171123174231-0010/2/./sparkling-water-assembly_2.11-2.2.0-all.jar to class loader
17/11/23 17:43:35 INFO TorrentBroadcast: Started reading broadcast variable 0
17/11/23 17:43:35 INFO TransportClientFactory: Successfully created connection to khanhpham2982/172.18.4.34:4641 after 58 ms (0 ms spent in bootstraps)
17/11/23 17:43:35 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 1379.0 B, free 1458.6 MB)
17/11/23 17:43:35 INFO TorrentBroadcast: Reading broadcast variable 0 took 347 ms
17/11/23 17:43:35 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 2.1 KB, free 1458.6 MB)
17/11/23 17:43:35 INFO MemoryStore: Block rdd_0_13 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:35 INFO MemoryStore: Block rdd_0_3 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:35 INFO Executor: 1 block locks were not released by TID = 13:
[rdd_0_13]
17/11/23 17:43:35 INFO Executor: 1 block locks were not released by TID = 3:
[rdd_0_3]
17/11/23 17:43:35 INFO Executor: Finished task 3.0 in stage 0.0 (TID 3). 1803 bytes result sent to driver
17/11/23 17:43:35 INFO Executor: Finished task 13.0 in stage 0.0 (TID 13). 1596 bytes result sent to driver
17/11/23 17:43:35 INFO CoarseGrainedExecutorBackend: Got assigned task 26
17/11/23 17:43:35 INFO Executor: Running task 26.0 in stage 0.0 (TID 26)
17/11/23 17:43:35 INFO CoarseGrainedExecutorBackend: Got assigned task 27
17/11/23 17:43:35 INFO Executor: Running task 27.0 in stage 0.0 (TID 27)
17/11/23 17:43:35 INFO MemoryStore: Block rdd_0_26 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:35 INFO MemoryStore: Block rdd_0_27 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:35 INFO Executor: 1 block locks were not released by TID = 26:
[rdd_0_26]
17/11/23 17:43:35 INFO Executor: 1 block locks were not released by TID = 27:
[rdd_0_27]
17/11/23 17:43:35 INFO Executor: Finished task 27.0 in stage 0.0 (TID 27). 1553 bytes result sent to driver
17/11/23 17:43:35 INFO Executor: Finished task 26.0 in stage 0.0 (TID 26). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 34
17/11/23 17:43:36 INFO Executor: Running task 34.0 in stage 0.0 (TID 34)
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 35
17/11/23 17:43:36 INFO Executor: Running task 35.0 in stage 0.0 (TID 35)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_34 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_35 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 34:
[rdd_0_34]
17/11/23 17:43:36 INFO Executor: Finished task 34.0 in stage 0.0 (TID 34). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 35:
[rdd_0_35]
17/11/23 17:43:36 INFO Executor: Finished task 35.0 in stage 0.0 (TID 35). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 41
17/11/23 17:43:36 INFO Executor: Running task 41.0 in stage 0.0 (TID 41)
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 42
17/11/23 17:43:36 INFO Executor: Running task 42.0 in stage 0.0 (TID 42)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_41 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_42 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 41:
[rdd_0_41]
17/11/23 17:43:36 INFO Executor: Finished task 41.0 in stage 0.0 (TID 41). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 42:
[rdd_0_42]
17/11/23 17:43:36 INFO Executor: Finished task 42.0 in stage 0.0 (TID 42). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 46
17/11/23 17:43:36 INFO Executor: Running task 46.0 in stage 0.0 (TID 46)
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 49
17/11/23 17:43:36 INFO Executor: Running task 49.0 in stage 0.0 (TID 49)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_46 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_49 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 46:
[rdd_0_46]
17/11/23 17:43:36 INFO Executor: Finished task 46.0 in stage 0.0 (TID 46). 1596 bytes result sent to driver
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 49:
[rdd_0_49]
17/11/23 17:43:36 INFO Executor: Finished task 49.0 in stage 0.0 (TID 49). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 54
17/11/23 17:43:36 INFO Executor: Running task 54.0 in stage 0.0 (TID 54)
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 55
17/11/23 17:43:36 INFO Executor: Running task 55.0 in stage 0.0 (TID 55)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_54 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_55 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 54:
[rdd_0_54]
17/11/23 17:43:36 INFO Executor: Finished task 54.0 in stage 0.0 (TID 54). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 55:
[rdd_0_55]
17/11/23 17:43:36 INFO Executor: Finished task 55.0 in stage 0.0 (TID 55). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 62
17/11/23 17:43:36 INFO Executor: Running task 62.0 in stage 0.0 (TID 62)
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 63
17/11/23 17:43:36 INFO Executor: Running task 63.0 in stage 0.0 (TID 63)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_62 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_63 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 62:
[rdd_0_62]
17/11/23 17:43:36 INFO Executor: Finished task 62.0 in stage 0.0 (TID 62). 1510 bytes result sent to driver
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 63:
[rdd_0_63]
17/11/23 17:43:36 INFO Executor: Finished task 63.0 in stage 0.0 (TID 63). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 69
17/11/23 17:43:36 INFO Executor: Running task 69.0 in stage 0.0 (TID 69)
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 71
17/11/23 17:43:36 INFO Executor: Running task 71.0 in stage 0.0 (TID 71)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_69 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_71 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 69:
[rdd_0_69]
17/11/23 17:43:36 INFO Executor: Finished task 69.0 in stage 0.0 (TID 69). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 71:
[rdd_0_71]
17/11/23 17:43:36 INFO Executor: Finished task 71.0 in stage 0.0 (TID 71). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 76
17/11/23 17:43:36 INFO Executor: Running task 76.0 in stage 0.0 (TID 76)
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 78
17/11/23 17:43:36 INFO Executor: Running task 78.0 in stage 0.0 (TID 78)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_76 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_78 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 76:
[rdd_0_76]
17/11/23 17:43:36 INFO Executor: Finished task 76.0 in stage 0.0 (TID 76). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 78:
[rdd_0_78]
17/11/23 17:43:36 INFO Executor: Finished task 78.0 in stage 0.0 (TID 78). 1553 bytes result sent to driver
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 83
17/11/23 17:43:36 INFO Executor: Running task 83.0 in stage 0.0 (TID 83)
17/11/23 17:43:36 INFO CoarseGrainedExecutorBackend: Got assigned task 86
17/11/23 17:43:36 INFO Executor: Running task 86.0 in stage 0.0 (TID 86)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_83 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO MemoryStore: Block rdd_0_86 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:36 INFO Executor: 1 block locks were not released by TID = 83:
[rdd_0_83]
17/11/23 17:43:36 INFO Executor: Finished task 83.0 in stage 0.0 (TID 83). 1553 bytes result sent to driver
17/11/23 17:43:37 INFO Executor: 1 block locks were not released by TID = 86:
[rdd_0_86]
17/11/23 17:43:37 INFO Executor: Finished task 86.0 in stage 0.0 (TID 86). 1553 bytes result sent to driver
17/11/23 17:43:37 INFO CoarseGrainedExecutorBackend: Got assigned task 92
17/11/23 17:43:37 INFO Executor: Running task 92.0 in stage 0.0 (TID 92)
17/11/23 17:43:37 INFO CoarseGrainedExecutorBackend: Got assigned task 93
17/11/23 17:43:37 INFO Executor: Running task 93.0 in stage 0.0 (TID 93)
17/11/23 17:43:37 INFO MemoryStore: Block rdd_0_92 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:37 INFO MemoryStore: Block rdd_0_93 stored as values in memory (estimated size 24.0 B, free 1458.6 MB)
17/11/23 17:43:37 INFO Executor: 1 block locks were not released by TID = 92:
[rdd_0_92]
17/11/23 17:43:37 INFO Executor: Finished task 92.0 in stage 0.0 (TID 92). 1510 bytes result sent to driver
17/11/23 17:43:37 INFO Executor: 1 block locks were not released by TID = 93:
[rdd_0_93]
17/11/23 17:43:37 INFO Executor: Finished task 93.0 in stage 0.0 (TID 93). 1553 bytes result sent to driver
17/11/23 17:43:38 INFO BlockManager: Removing RDD 0
17/11/23 17:43:38 INFO CoarseGrainedExecutorBackend: Got assigned task 101
17/11/23 17:43:38 INFO Executor: Running task 2.0 in stage 1.0 (TID 101)
17/11/23 17:43:38 INFO TorrentBroadcast: Started reading broadcast variable 1
17/11/23 17:43:38 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 2.0 KB, free 1458.6 MB)
17/11/23 17:43:38 INFO TorrentBroadcast: Reading broadcast variable 1 took 9 ms
17/11/23 17:43:38 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 3.3 KB, free 1458.6 MB)
17/11/23 17:43:38 INFO NativeLibrary: Loaded XGBoost library from lib/linux_64/libxgboost4j.so (/tmp/libxgboost4j8903247784921411757.so)
17/11/23 17:43:39 INFO Executor: Finished task 2.0 in stage 1.0 (TID 101). 1780 bytes result sent to driver
17/11/23 17:43:39 INFO CoarseGrainedExecutorBackend: Got assigned task 116
17/11/23 17:43:39 INFO Executor: Running task 6.3 in stage 1.0 (TID 116)
17/11/23 17:43:39 ERROR Executor: Exception in task 6.3 in stage 1.0 (TID 116)
java.lang.AssertionError: assertion failed: SpreadRDD failure - IPs are not equal: (6,172.18.12.84,-1) != (2, 172.18.12.179)
	at scala.Predef$.assert(Predef.scala:170)
	at org.apache.spark.h2o.backends.internal.InternalBackendUtils$$anonfun$7.apply(InternalBackendUtils.scala:101)
	at org.apache.spark.h2o.backends.internal.InternalBackendUtils$$anonfun$7.apply(InternalBackendUtils.scala:100)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/11/23 17:48:59 INFO BlockManager: Removing RDD 0`

**Comment by jakubhava** [comment]
Can you pls describe your environment a bit more ? Do you have firewalls in place, hw nodes connected to multiple networks ?

Also please read through this issue where this problem is resolved - https://github.com/h2oai/sparkling-water/issues/433

Thanks!

**Comment by cazjck** [comment]
Hi @jakubhava 
I have 2 machine Ubuntu 14.4, 2 machine Windown 7 and Master node (StandAlone mode) run in Ubuntu environment. In the Ubuntu OS, I disable firewall with cmd: `sudo ufw disable` .
In the Network between Ubuntus and Windown, I have 172.18.4.x and 172.18.12.x, I think this is same the network. Because I try run 2 machine ubuntu with IP : 172.18.12.x but i still get the error.
In Local mode. i run `h2o_context(sc)` success.
My configuration in R code:
`options(spark.install.dir="D:/Spark/")
options(java.parameters = "-Xmx2048m") 
Sys.setenv(HADOOP_CONF_DIR = "D:/hadoop/etc/hadoop")
Sys.setenv(YARN_CONF_DIR = "D:/hadoop/etc/hadoop")
Sys.setenv(SPARK_HOME = "D:/Spark//spark-2.2.0-bin-hadoop2.7")
options(rsparkling.sparklingwater.location = "packages/sparkling-water-2.2.0/assembly/build/libs/sparkling-water-assembly_2.11-2.2.0-all.jar")
library(rsparkling)
library(sparklyr)
options(spark.install.dir="D:/Spark/")
library(h2o)
library(dplyr)
library(pryr)
conf <- spark_config()
conf$'sparklyr.shell.driver-memory' <- "4g"
conf$'spark.driver.host'<-"clientA"
conf$'spark.network.timeout'<-500
conf$spark.executor.cores <- 2
conf$spark.executor.memory <- "3G"
conf$sparklyr.gateway.start.timeout <- 60 * 5"
sc <- spark_connect(master = "spark://master:7077",app_name = "sparklyr tester",config = conf)`

Thanks

**Comment by jakubhava** [comment]
Can you run the whole setup just on a single platform ? Just to see if this has anything to do with it.

Also, in Sparkling Water we use the IP address provided by Spark which in some environments is not what we want. We can override this by h2o client network & mask and h2o nodes network & mask. More info is here https://github.com/h2oai/sparkling-water/blob/master/doc/configuration/configuration_properties.rst . Look for `spark.ext.h2o.client.network.mask` for client node ( h2o running on spark driver ) and `spark.ext.h2o.node.network.mask` for h2o nodes in spark executors. So I would try to start H2OContext as this if the issue remains which sets these 2 configuration propetries:
```
val conf = new H2OConf(sparkSession).setClientNetworkMask("mask_for_h2o_client").setNodeNetworkMask("mask_for_h2o_nodes")
val h2oContext = H2OContext.getOrCreate(sparkSession, conf)
```

You can also use `setClienIP` which doesn't specify the network, but ip directly

**Comment by cazjck** [comment]
I already run only Ubuntu OS this still get the error. I will try override network

**Comment by cazjck** [comment]
Hi @jakubhava 
I resolved the issues .
Root cause: edit config in /etc/hosts . I removed line:  127.0.1.1 myMachine

**Comment by bharathwgl** [comment]
I am getting the same error:

SpreadRDD failure - IPs are not equal: 
Please provide some inputs
